import { test } from "node:test";
import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { createInterface } from "node:readline";
import { once } from "node:events";
import { fixture } from "./fixture.js";
import { State } from "../src/state.js";
import { tickQueue } from "../src/queue.js";
import { createCli } from "../src/cli.js";

test("stdio MCP advertises schemas and runs the same read and write commands", { timeout: 20_000 }, async t => {
  const f = await fixture(t), state = new State(f.dir + "/state");
  state.put("worker", "lease", { owner: "test", pid: process.pid });
  const child = spawn(process.execPath, ["--import", "tsx", "src/bin.ts", "--mcp"], { stdio: ["pipe", "pipe", "pipe"], env: { ...process.env, T3THREADS_STATE_DIR: state.directory } });
  const pending = new Map<number, (value: any) => void>();
  let nextID = 1, stderr = "";
  child.stderr.on("data", data => { stderr += String(data); });
  const lines = createInterface({ input: child.stdout });
  lines.on("line", line => {
    const message = JSON.parse(line);
    if (message.id) { pending.get(message.id)?.(message); pending.delete(message.id); }
  });
  t.after(async () => {
    lines.close();
    const ended = once(child, "exit");
    let forced = false;
    const timer = setTimeout(() => { forced = true; child.kill("SIGKILL"); }, 3000);
    child.kill("SIGTERM");
    await ended;
    clearTimeout(timer);
    assert.equal(forced, false, "MCP server should exit on SIGTERM");
  });
  const call = (method: string, params: object = {}) => {
    const id = nextID++;
    return new Promise<any>((resolve, reject) => {
      const timer = setTimeout(() => reject(Error(`MCP timeout: ${method}; ${stderr}`)), 8000);
      pending.set(id, result => { clearTimeout(timer); resolve(result); });
      child.stdin.write(JSON.stringify({ jsonrpc: "2.0", id, method, params }) + "\n");
    });
  };
  const initialized = await call("initialize", { protocolVersion: "2025-11-25", capabilities: {}, clientInfo: { name: "t3threads-test", version: "1" } });
  assert.equal(initialized.result.serverInfo.name, "t3threads");
  child.stdin.write(JSON.stringify({ jsonrpc: "2.0", method: "notifications/initialized" }) + "\n");
  const listed = await call("tools/list");
  const tools = listed.result.tools as { name: string; annotations: { readOnlyHint: boolean; idempotentHint: boolean }; inputSchema: { properties: Record<string, unknown>; required?: string[] } }[];
  assert.deepEqual(tools.map(t => t.name).sort(), ["classify", "doctor", "environments", "find", "list", "manage", "overview", "projects", "queued", "read", "search", "send", "start", "summarize", "unqueue", "unwatch", "watch", "watchers"]);
  assert.equal(tools.find(t => t.name === "read")?.annotations.readOnlyHint, true);
  assert.equal(tools.find(t => t.name === "start")?.annotations.readOnlyHint, false);
  assert.equal(tools.find(t => t.name === "start")?.annotations.idempotentHint, false);
  assert.ok(tools.find(t => t.name === "read")?.inputSchema.properties.env);
  assert.equal(tools.find(t => t.name === "watch")?.annotations.readOnlyHint, false);
  assert.ok(tools.find(t => t.name === "watch")?.inputSchema.properties.condition);
  assert.ok(tools.find(t => t.name === "send")?.inputSchema.properties.caller);
  assert.ok(tools.find(t => t.name === "send")?.inputSchema.properties.externalCaller);
  assert.ok(tools.find(t => t.name === "send")?.inputSchema.properties.steer);
  assert.ok(tools.find(t => t.name === "send")?.inputSchema.properties.enqueue);
  assert.equal(tools.find(t => t.name === "queued")?.annotations.readOnlyHint, true);
  assert.equal(tools.find(t => t.name === "unqueue")?.annotations.readOnlyHint, false);
  const overview = await call("tools/call", { name: "overview", arguments: { config: f.configPath, env: "local" } });
  assert.ok(!overview.result.isError, JSON.stringify(overview));
  assert.ok(JSON.stringify(overview.result).includes("local:t1"));
  const doctor = await call("tools/call", { name: "doctor", arguments: { config: f.configPath } });
  assert.ok(!doctor.result.isError, JSON.stringify(doctor));
  const start = await call("tools/call", { name: "start", arguments: { config: f.configPath, project: "p1", checkout: "worktree", branch: "main", prompt: "Review this task" } });
  assert.ok(!start.result.isError, JSON.stringify(start));
  assert.equal(f.commands.length, 1);
  const read = await call("tools/call", { name: "read", arguments: { config: f.configPath, thread: f.commands[0]!.threadId } });
  assert.ok(!read.result.isError, JSON.stringify(read));
  assert.ok(JSON.stringify(read.result).includes("Review this task"));
  const missingCaller = await call("tools/call", { name: "send", arguments: { config: f.configPath, thread: f.commands[0]!.threadId, prompt: "Check the tests." } });
  assert.equal(missingCaller.result.isError, true);
  assert.equal(f.commands.length, 1);
  const sent = await call("tools/call", { name: "send", arguments: { config: f.configPath, thread: f.commands[0]!.threadId, caller: "local:t1", prompt: "Check the tests." } });
  assert.ok(!sent.result.isError, JSON.stringify(sent));
  assert.match(JSON.stringify(sent.result), /queued/);
  await tickQueue(state);
  assert.equal(f.commands.length, 2);
  assert.match(f.commands[1]!.message.text, /Sender thread: local:t1/);
  assert.match(f.commands[1]!.message.text, /from another agent, not the user/);
  assert.ok(f.commands[1]!.message.text.endsWith("\n\nCheck the tests."));
  f.stored.get("t1")!.latestTurn = { state: "running" };
  const steered = await call("tools/call", { name: "send", arguments: { config: f.configPath, thread: "t1", caller: "local:t1", prompt: "Continue now.", steer: true } });
  assert.ok(!steered.result.isError, JSON.stringify(steered));
  await tickQueue(state);
  assert.equal(f.commands.length, 3);
  const external = await call("tools/call", { name: "send", arguments: { config: f.configPath, thread: "t1", externalCaller: "jessbot", prompt: "Ada sent a Slack follow-up.", steer: true } });
  assert.ok(!external.result.isError, JSON.stringify(external));
  assert.equal(f.commands.length, 4);
  assert.match(f.commands[3]!.message.text, /external caller "jessbot"/);
  const bothCallers = await call("tools/call", { name: "send", arguments: { config: f.configPath, thread: "t1", caller: "local:t1", externalCaller: "jessbot", prompt: "Continue.", steer: true } });
  assert.equal(bothCallers.result.isError, true);
  assert.equal(f.commands.length, 4);
  const invalid = await call("tools/call", { name: "read", arguments: { config: f.configPath, thread: "t1", turns: 0 } });
  assert.equal(invalid.result.isError, true);
  assert.ok(!stderr.includes("test-secret"));
});

test("Fetch surface includes OpenAPI and HTTP MCP discovery", async () => {
  const cli = createCli();
  const schema = await (await cli.fetch(new Request("http://cli/openapi.json"))).json() as { paths: Record<string, unknown> };
  assert.ok(Object.keys(schema.paths).some(p => p.includes("start")));
  const response = await cli.fetch(new Request("http://cli/mcp", { method: "POST", headers: { "content-type": "application/json", accept: "application/json, text/event-stream" }, body: JSON.stringify({ jsonrpc: "2.0", id: 1, method: "initialize", params: { protocolVersion: "2025-11-25", capabilities: {}, clientInfo: { name: "test", version: "1" } } }) }));
  assert.equal(response.status, 200);
  assert.ok((await response.text()).includes("t3threads"));
});
